print("...........Student Details.............")
name= input("Enter Name:")
college= input("Enter College Name:")
rollNo= int(input("Enter Roll No.:"))
studentNo= int(input("Enter Student no.:"))
add= input("Address:")
age= int(input("Enter Age:"))
print("...........Type............")
print(type(name))
print(type(college))
print(type(rollNo))
print(type(studentNo))
print (type(add))
print(type(age))
print("..............Student Data...............")
print("Name:",name)
print("College:",college)
print("Roll No.:",rollNo)
print("Student No.:",studentNo)
print("Address:",add)
print("Age:",age)